### ISSUE TITLE
Convert into a composite action

### ISSUE THREAD

**Issue by excitedleigh** [excitedleigh/setup-nox#186]
Since this is essentially a fork of actions/setup-python that sets up _all_ the Pythons and then does some stuff afterwards, it might be an idea to turn this into a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) now that those exist.

**Comment by henryiii** [comment]
Composite actions can't run other actions, only run steps with shell's (no ifs, either). At least last I checked when I wrote https://github.com/joerick/cibuildwheel/blob/master/action.yml .
