### ISSUE TITLE
Builds dependent on setup-nox fail due to add-path command removal from Actions core package

### ISSUE THREAD

**Issue by RonquilloAeon** [excitedleigh/setup-nox#235]
See https://github.com/actions/toolkit/issues/643

**Comment by EugenWiens** [comment]
I have the same Problem:
![image](https://user-images.githubusercontent.com/7880602/99732682-32d77300-2ac0-11eb-88b7-267cab1695ea.png)

**Comment by e-k-m** [comment]
This issue still exists. Are there any plans to resolve it? Or is the project deprecated? Thanks for a feedback.

**Comment by henryiii** [comment]
@excitedleigh should be able to just bump dependencies to fix this; the latest GH-core does this safely.

**Comment by henryiii** [comment]
Because this is a fork of an official action, it might actually more more complicated than that.

**Comment by excitedleigh** [comment]
Hey folks! Sorry for the delay, but I'm releasing a fix for this now :)

**Comment by e-k-m** [comment]
THX

**Comment by henryiii** [comment]
Ooh, that looks so much cleaner. :)

**Comment by henryiii** [comment]
Your readme still has an example pinning to v1.0.0...
